### ISSUE TITLE
Gridded crop yield

### ISSUE THREAD

**Issue by miquel-espinosa** [chc-ucsb/gscd#4]
Hi. Is it possible to get this crop yield data gridded, into a shapefile? Is there any code to do that?

**Comment by gnodnooh** [comment]
Thank you for your inquiry. Although we are heavily working on the gridded data, we do not currently and officially provide or make the data public for a variety of reasons. We will update this once we have a proper journal publication for citation.

**Comment by WestonAnderson** [comment]
Hi Donghoon,

I realized this relates to a collaborator specifically working with the data in Zambia. I am going to provide them with the gridded data for Zambia, but I agree that we should continue to not make it public. I’ve found some issues with the gridding script that I’ll need to clean up after I return from vacation next week

Best,
Weston

From: Donghoon Lee ***@***.***>
Reply-To: chc-ucsb/gscd ***@***.***>
Date: Thursday, May 18, 2023 at 3:10 PM
To: chc-ucsb/gscd ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [BULK] Re: [chc-ucsb/gscd] Gridded crop yield (Issue #4)

CAUTION: This email originated from outside of NASA.  Please take care when clicking links or opening attachments.  Use the "Report Message" button to report suspicious messages to the NASA SOC.



Thank you for your inquiry. Although we are heavily working on the gridded data, we do not currently and officially provide or make the data public for a variety of reasons. We will update this once we have a proper journal publication for citation.

**Comment by WestonAnderson** [comment]
Followed up by email. Gridding script will be made public once it is thoroughly tested.
